// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDewQMsUpQWaDYZ3QZ4paMVRvCzC1PHkFY',
    appId: '1:62154048427:web:3e0a85ffed88ece192c8ee',
    messagingSenderId: '62154048427',
    projectId: 'social-media-app-5f00e',
    authDomain: 'social-media-app-5f00e.firebaseapp.com',
    storageBucket: 'social-media-app-5f00e.firebasestorage.app',
    measurementId: 'G-TVX23JJK2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuY2jq8VvWm2B3qkw0KZPmRqxgBokloGM',
    appId: '1:62154048427:android:bb9b9bbdcb7f916992c8ee',
    messagingSenderId: '62154048427',
    projectId: 'social-media-app-5f00e',
    storageBucket: 'social-media-app-5f00e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj-raKmr7-Mf7GgQ0_IT6iPPgFa8D3r_M',
    appId: '1:62154048427:ios:bdfd86d5bf2527ed92c8ee',
    messagingSenderId: '62154048427',
    projectId: 'social-media-app-5f00e',
    storageBucket: 'social-media-app-5f00e.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj-raKmr7-Mf7GgQ0_IT6iPPgFa8D3r_M',
    appId: '1:62154048427:ios:bdfd86d5bf2527ed92c8ee',
    messagingSenderId: '62154048427',
    projectId: 'social-media-app-5f00e',
    storageBucket: 'social-media-app-5f00e.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDewQMsUpQWaDYZ3QZ4paMVRvCzC1PHkFY',
    appId: '1:62154048427:web:2638d68b4156df1692c8ee',
    messagingSenderId: '62154048427',
    projectId: 'social-media-app-5f00e',
    authDomain: 'social-media-app-5f00e.firebaseapp.com',
    storageBucket: 'social-media-app-5f00e.firebasestorage.app',
    measurementId: 'G-XX5CS04EF1',
  );
}
